export type UserID = string;

export interface CollaborationUser {
  id: UserID;
  name: string;
  color: string;
}

export interface DocumentChange {
  /** Incremental version number of the document */
  version: number;
  /** Operations generated by the CRDT strategy */
  ops: any[];
}

export type CollaborationMessageType = 'change' | 'presence' | 'join' | 'leave';

export interface CollaborationMessage {
  type: CollaborationMessageType;
  /** Payload varies by message type */
  payload: any;
}
