/**
 * Simple conflict resolver for collaborative text editing.
 * Uses a last‑write‑wins strategy based on a monotonically increasing timestamp.
 * Each edit operation should include a `timestamp` field generated by the client.
 * The resolver prefers the operation with the newer timestamp.
 *
 * While this is not as sophisticated as CRDT/OT, it provides deterministic
 * conflict handling without additional heavy dependencies.
 */

export interface EditOperation {
  /** Full document content after the edit */
  content: string;
  /** Milliseconds since epoch generated by the client */
  timestamp: number;
}

/**
 * Resolve two concurrent edit operations.
 * Returns the operation that should win.
 */
export function resolveConflict(local: EditOperation, remote: EditOperation): EditOperation {
  if (!remote) return local;
  if (!local) return remote;
  return remote.timestamp > local.timestamp ? remote : local;
}

/**
 * Apply a resolved operation to the current editor state.
 */
export function applyEdit(currentContent: string, operation: EditOperation): string {
  return operation ? operation.content : currentContent;
}
