import type { EditorOperation, DocumentState } from '../types/editor';
import type { WebSocketMessage } from '../types/websocketMessage';

/**
 * Simple version‑based conflict resolver.
 *
 * Each operation carries a monotonically increasing `version` generated by the
 * server. The client applies operations only if they are newer than the current
 * document version. Out‑of‑order operations are stored in a pending map and
 * re‑applied when missing intermediate versions arrive.
 */
export class ConflictResolver {
  private version: number = 0;
  private pending: Map<number, EditorOperation> = new Map();

  constructor(private applyFn: (op: EditorOperation) => void) {}

  /**
   * Process an incoming operation message.
   */
  public handleMessage(msg: WebSocketMessage) {
    if (msg.type !== 'operation') return;
    const op: EditorOperation = msg.payload.operation;
    const incomingVersion = op.version;
    if (incomingVersion === this.version + 1) {
      this.apply(op);
      this.version = incomingVersion;
      this.flushPending();
    } else if (incomingVersion > this.version + 1) {
      // Future operation – store for later
      this.pending.set(incomingVersion, op);
    } // else: duplicate or old operation – ignore
  }

  /**
   * Apply an operation and invoke the supplied apply function.
   */
  private apply(op: EditorOperation) {
    this.applyFn(op);
  }

  /**
   * Attempt to apply any pending operations that now have a contiguous version.
   */
  private flushPending() {
    let next = this.version + 1;
    while (this.pending.has(next)) {
      const op = this.pending.get(next)!;
      this.pending.delete(next);
      this.apply(op);
      this.version = next;
      next += 1;
    }
  }

  /**
   * Generate a local operation with the next version number.
   * Caller should send the resulting message to the server.
   */
  public createLocalOperation(change: Partial<DocumentState>): EditorOperation {
    const op: EditorOperation = {
      version: this.version + 1,
      change,
    };
    // Optimistically apply locally
    this.apply(op);
    this.version = op.version;
    this.flushPending();
    return op;
  }
}
